
use [RoC];

---UPDATE QUERY FOR BANGALORE URBAN
UPDATE [dbo].[ROC Revised]
SET [District] = 'Bengaluru Urban'
WHERE [Row_ID] IN (
    SELECT [Row_ID] 
FROM [dbo].[ROC Revised]
WHERE (
    Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%abbigere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%adugodi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%anekal%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%attibele%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babgalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bagalagunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banaglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore south%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore urban%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basavanagudi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basngalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bellandur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalooru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bidarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%btm%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabanavara%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabellandur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabidarakallu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkagubbi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasanapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devagere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devasandra%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%electronic city%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%elenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%gandhinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hanumanthnagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hebbala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hesaraghatta%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%horamavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hoskote%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hulimavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jalahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jigani%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kamakshipalya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kengeri%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodihalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodipalya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%koramangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mahadevapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%malleshwaram%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi main road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%marathahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mysore road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nagarabhavi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%peenya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumkur road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumakuru road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsuru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsoor%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%uttarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijanapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijayanagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%viveknagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%whitefield%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yalahanka%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yarappanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeshwanthpur%'
)
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%';



--update query for bangalore --- dont update just execute the sub query below first

--SUBQUERY FOR BANGALORE URBAN


SELECT [Row_ID], [Registered_Office_Address_Cleaned]
FROM [dbo].[ROC Revised]
WHERE (
    Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%abbigere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%adugodi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%anekal%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%attibele%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babgalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bagalagunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banaglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore south%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore urban%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basavanagudi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basngalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bellandur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalooru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bidarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%btm%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabanavara%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabellandur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabidarakallu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkagubbi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasanapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devagere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devasandra%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%electronic city%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%elenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%gandhinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hanumanthnagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hebbala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hesaraghatta%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%horamavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hoskote%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hulimavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jalahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jigani%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kamakshipalya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kengeri%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodihalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodipalya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%koramangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mahadevapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%malleshwaram%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi main road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%marathahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mysore road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nagarabhavi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%peenya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumkur road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumakuru road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsuru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsoor%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%uttarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijanapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijayanagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%viveknagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%whitefield%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yalahanka%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yarappanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeshwanthpur%'
)
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%'

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%banagalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hoskote%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddaballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangaluru rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%manchanabele%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%agara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%arasinakunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kannamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jinkebachalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devarahosahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yentaganahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagaram%'


AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara%'           
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary%';
--subquery to just fetch the places of bangalore




--for bangalore rural updation

UPDATE [dbo].[ROC Revised]
SET [District] = 'Bengaluru Rural'
WHERE [Row_ID] IN (
SELECT [Row_ID]
FROM [dbo].[ROC Revised]
WHERE (
(
    Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hoskote%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%doddaballapur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nelamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%veerapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bashettihalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vishwanathapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%binnamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%thindlu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%manchanabele%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%arasinakunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mallur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kannamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jinkebachalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devarahosahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yentaganahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bychapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%budigere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bettahalasur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sompura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sulikunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kerehalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodigehalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere hobli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bommenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore rural%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangaluru rural%'
)


 

    --OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramanagaram%'
)

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%abbigere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%adugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%agara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anekal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%attibele%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalagunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore south%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore urban%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%basavanagudi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%basaveshwaranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellandur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengalooru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bidarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%btm%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chamarajanagara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chamrajnagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%channapatana%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chickmagalur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabellandur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabidarakallu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabanavara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkagubbi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikmagalur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chitradurga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasanapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%davanagere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devagere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharrwad%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%electronic city%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%elenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gadag%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gandhinagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hanumanthnagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hebbala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hesaraghatta%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%horamavu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubblli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hulimavu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranager%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar 1st stage%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar 2nd stage%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indira nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jalahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jakkasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jayanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jigani%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jp nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%j p nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamakshipalya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kammanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kammagondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kalyan nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kengeri%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodipalya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%koramangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kormangalam%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi main road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mahadevapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%malleshwaram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%marathahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%madiwala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mg road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%munnekolalu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nagarabhavi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%new thippasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%peenya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%pulikeshi nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%pulkeshi nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramagondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagaram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rajaji nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rajajinagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rt nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rv road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sadashivanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sahakara nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sahakaranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sarjapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sarjapur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%singasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%srirampuram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%subramanyapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tilaknagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%telecom layout%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumakuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumakuru road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ulsuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ulsoor%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%uttarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%uttara kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijanapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vidyaranyapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%whitefield%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yalahanka%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yekkanhalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yeshwanthpur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yeswanthpura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%banashankari%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hosakerehalli%'









--for bangalore rural fetching through subquery;



SELECT [Row_ID], [Registered_Office_Address_Cleaned]
FROM [dbo].[ROC Revised]
WHERE (
       Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hoskote%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%doddaballapur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nelamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%veerapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bashettihalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vishwanathapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%binnamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%thindlu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%manchanabele%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%arasinakunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mallur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kannamangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jinkebachalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devarahosahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yentaganahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bychapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%budigere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bettahalasur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sompura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sulikunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kerehalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodigehalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere hobli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bommenahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore rural%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangaluru rural%'
)

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%abbigere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%adugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%agara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anekal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%attibele%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalagunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore south%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore urban%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%basavanagudi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%basaveshwaranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellandur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengalooru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bidarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%btm%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chamarajanagara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chamrajnagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%channapatana%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chickmagalur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabellandur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabidarakallu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabanavara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkagubbi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikmagalur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chitradurga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasanapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%davanagere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devagere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharrwad%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%electronic city%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%elenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gadag%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gandhinagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hanumanthnagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hebbala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hesaraghatta%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%horamavu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubblli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hulimavu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranager%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar 1st stage%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indiranagar 2nd stage%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%indira nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jalahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jakkasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jayanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jigani%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jp nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%j p nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamakshipalya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kammanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kammagondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kalyan nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kengeri%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodipalya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%koramangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kormangalam%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi main road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mahadevapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%malleshwaram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%marathahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%madiwala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mg road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%munnekolalu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nagarabhavi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%new thippasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%peenya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%pulikeshi nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%pulkeshi nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramagondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagaram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rajaji nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rajajinagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rt nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%rv road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sadashivanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sahakara nagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sahakaranagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sarjapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sarjapur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%singasandra%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%srirampuram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%subramanyapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tilaknagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%telecom layout%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumakuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumakuru road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ulsuru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ulsoor%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%uttarahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%uttara kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijanapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vidyaranyapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%whitefield%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yalahanka%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yekkanhalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yeshwanthpur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yeswanthpura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%banashankari%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hosakerehalli%';