


use [RoC];

--SUBQUERY FOR BANGALORE URBAN--


SELECT [Row_ID], [Registered_Office_Address_Cleaned]
FROM [dbo].[ROC Revised]
WHERE (
    Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%abbigere%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%adugodi%'
    --OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%agara%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore south%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore urban%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basavanagudi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basaveshwaranagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bellandur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%btm%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranager%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 1st stage%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 2nd stage%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indira nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jalahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jakkasandra%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jayanagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jp nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%j p nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kadugodi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kamakshipalya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kalyan nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kengeri%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodihalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%koramangala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kormangalam%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mahadevapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%malleshwaram%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%marathahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%madiwala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mg road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%munnekolalu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nagarabhavi%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%new thippasandra%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%peenya%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulikeshi nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulkeshinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rajajinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rajaji nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rt nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rv road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sadashivanagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakara nagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakaranagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapur road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%singasandra%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%srirampuram%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%subramanyapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tilaknagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%telecom layout%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsuru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsoor%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%uttarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijanapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijayanagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%whitefield%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yalahanka%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeshwanthpura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeswanthpura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banashankari%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hosakerehalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banashankari iii stage%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hosakerehalli cross%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%girinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hsr layout%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hennur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%horamavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapur road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kengeri%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yelahanka%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hessarghatta%'

    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babgalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bagalagunte%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banaglore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore south%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore urban%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basngalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalooru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru urban%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru north%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru south%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%b''lroe%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basngalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangaloru%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babgalore%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babglore%'
---guddi query
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranager%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 1st stage%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 2nd stage%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indira nagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kormangalam%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mg road%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%munnekolalu%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%new thippasandra%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulikeshi nagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulkeshinagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rajaji nagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rt nagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rv road%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakara nagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakaranagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%singasandra%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%srirampuram%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%subramanyapura%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tilaknagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%telecom layout%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsuru%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsoor%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%whitefield%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yarappanahalli%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeswanthpura%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banashankari iii stage%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hosakerehalli cross%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%girinagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hsr layout%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hennur%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%horamavu%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabidarakallu%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkagubbi%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabellandur%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bidarahalli%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasanapura%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devagere%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devasandra%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%elenahalli%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%gandhinagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hanumanthnagar%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hebbala%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hesaraghatta%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hulimavu%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jigani%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodipalya%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi main road%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi road%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramagondanahalli%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapura%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumakuru road%'
OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%viveknagar%'

---chethan
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%anekal%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%attibele%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%electronic city%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapura%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jigani%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hulimavu%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hebbala%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeshwanthpur%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasarahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%gandhinagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hanumanthnagar%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi main road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mysore road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramagondanahalli%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumakuru road%'
    OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%viveknagar%'
)

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hoskote%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddaballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%veerapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bashettihalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vishwanathapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%binnamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thindlu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%manchanabele%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%arasinakunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kannamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jinkebachalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devarahosahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yentaganahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bychapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%budigere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bettahalasur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sompura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sulikunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kerehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodigehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavarekere hobli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bommenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangaluru rural%'

AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%banagalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hoskote%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddaballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadugodi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%manchanabele%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%agara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%arasinakunte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kannamangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jinkebachalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devarahosahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yentaganahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagaram%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara%' 


AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala town%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavrekere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thavarekere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodi halli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nandidurga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%garehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%badami%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kudligi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkanayakanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakpura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%raichur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anugondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodda,ballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodagu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%halehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nel,mangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sunkadakatte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kc valley%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddabellapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shimoga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gachibowli serilingampally%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapur main road%'


AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%saklespur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharwad%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gulbarga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysuru%'


----guddi 
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala town%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavrekere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thavarekere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodi halli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nandidurga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%garehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%badami%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kudligi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkanayakanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakpura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%raichur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anugondanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodda,ballapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodagu%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%halehalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nel,mangala%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sunkadakatte%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kc valley%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddabellapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shimoga%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gachibowli serilingampally%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapur main road%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%davanagere%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bidar%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mudhol%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramdurg%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shiralakoppa%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gokak%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bylakonenahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharwad%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sirsi%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sannatammanahalli%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%koppal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sira%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru rural%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandikal%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hosakote%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddballapura%'

---chethan
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabanavara%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasanapura%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hesaraghatta%'
AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavarekere%' 
;

SELECT TOP 10 * 
FROM [dbo].[ROC Revised];


----Update query for Bangaluru Urban

UPDATE [dbo].[ROC Revised]
SET [District] = 'Bengaluru Urban'
WHERE [Row_ID] IN (
    SELECT [Row_ID]
    FROM [dbo].[ROC Revised]
    WHERE (
        Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%abbigere%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%adugodi%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%anekal%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%attibele%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babgalore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%babglore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bagalagunte%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banaglore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengalooru%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru urban%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru north%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bengaluru south%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore south%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bangalore urban%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basngalore%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basavanagudi%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%basaveshwaranagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bellandur%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%btm%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranager%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 1st stage%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indiranagar 2nd stage%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%indira nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jalahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jakkasandra%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jayanagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jp nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%j p nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kadugodi%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kamakshipalya%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammanahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kammagondanahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kalyan nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kengeri%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodihalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%koramangala%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kormangalam%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mahadevapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%malleshwaram%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%marathahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%madiwala%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%mg road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%munnekolalu%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%nagarabhavi%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%new thippasandra%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%peenya%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulikeshi nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%pulkeshinagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rajajinagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rajaji nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rt nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%rv road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sadashivanagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakara nagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sahakaranagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapur road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%singasandra%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%srirampuram%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%subramanyapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tilaknagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%telecom layout%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsuru%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ulsoor%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%uttarahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijanapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%vijayanagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%whitefield%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yalahanka%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeshwanthpura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%yeswanthpura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banashankari%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hosakerehalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%banashankari iii stage%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hosakerehalli cross%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%girinagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hsr layout%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hennur%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%horamavu%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kanakapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabidarakallu%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkagubbi%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%chikkabellandur%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%bidarahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%dasanapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devagere%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%devasandra%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%elenahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%gandhinagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hanumanthnagar%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hebbala%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hesaraghatta%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%hulimavu%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%jigani%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%kodipalya%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi main road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%magdi road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%ramagondanahalli%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%sarjapura%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tavarekere%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%tumakuru road%'
        OR Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI LIKE '%viveknagar%'
    )
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hoskote%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddaballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%veerapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bashettihalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vishwanathapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%binnamangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thindlu%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%manchanabele%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%arasinakunte%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasenahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kannamangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jinkebachalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devarahosahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yentaganahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bychapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%budigere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bettahalasur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sompura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sulikunte%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kerehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodigehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavarekere hobli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bommenahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangaluru rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysore road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hassan road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%belgaum%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kolar%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%banagalore rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mangaluru%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hoskote%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddaballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magadi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadugodi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%manchanabele%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%agara%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakapura road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%arasinakunte%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasenahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mallur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kannamangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%jinkebachalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%devarahosahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%yentaganahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagaram%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bellary%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagar%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramanagara%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala town%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavrekere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thavarekere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodi halli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nandidurga%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%garehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%badami%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kudligi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkanayakanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakpura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%raichur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihal%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anugondanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodda,ballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodagu%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%halehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nel,mangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sunkadakatte%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kc valley%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddabellapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shimoga%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gachibowli serilingampally%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapur main road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%saklespur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharwad%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tumkur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gulbarga%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mysuru%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%vijayapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nelamangala town%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kamanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%magdi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavrekere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%thavarekere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodi halli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nandidurga%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%garehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bagalkot%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%badami%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kudligi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkanayakanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkaballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kanakpura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%raichur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodihal%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%anugondanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodda,ballapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kodagu%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%halehalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%nel,mangala%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sunkadakatte%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kc valley%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddabellapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shimoga%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dakshina kannada%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gachibowli serilingampally%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%challakere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hubli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dodballapur main road%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%davanagere%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bidar%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%kadur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mudhol%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%ramdurg%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%shiralakoppa%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%gokak%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bylakonenahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dharwad%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sirsi%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sannatammanahalli%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bijapur%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandya%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%koppal%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%sira%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bangalore rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%bengaluru rural%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%mandikal%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hosakote%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%doddballapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%chikkabanavara%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%dasanapura%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%hesaraghatta%'
    AND Registered_Office_Address_Cleaned COLLATE Latin1_General_CI_AI NOT LIKE '%tavarekere%'
);
